theme = "boo_berry"

[editor]
line-number = "relative"
auto-completion = true
text-width = 80
bufferline = "multiple"

[keys.normal]
f = "move_next_word_end"
F = "move_next_long_word_end"
p = "replace"
P = "replace_with_yanked"
g = "find_till_char"
G = "find_prev_char"
j = "yank"
l = "undo"
L = "redo"
u = "insert_mode"
U = "insert_at_line_start"
y = "open_below"
Y = "open_above"
";" = "paste_after"
":" = "paste_before"
r = "select_regex"
R = "split_selection"
s = "delete_selection"
t = "find_next_char"
T = "find_prev_char"
D = "goto_line"
n = "move_visual_line_down"
N = "join_selections"
e = "move_visual_line_up"
E = "keep_selections"
i = "move_char_right"
o = "collapse_selection"
O = "command_mode"
k = "search_next"
K = "search_prev"

C-f = "page_down"
C-s = "page_cursor_half_down"
C-l = "page_cursor_half_up"
C-u = "jump_forward"
C-y = "jump_backward"
C-r = "save_selection"

[keys.normal.d]
"d" = "goto_file_start"
"f" = "goto_last_line"
"t" = "goto_file"
"h" = "goto_line_start"
"i" = "goto_line_end"
"r" = "goto_first_nonwhitespace"
"g" = "goto_window_top"
"c" = "goto_window_center"
"b" = "goto_window_bottom"
"s" = "goto_definition"
"j" = "goto_type_definition"
"p" = "goto_reference"
"u" = "goto_implementation"
"k" = "goto_next_buffer"
";" = "goto_previous_buffer"
"n" = "move_line_down"
"e" = "move_line_up"

[keys.select]
f = "move_next_word_end"
F = "move_next_long_word_end"
p = "replace"
P = "replace_with_yanked"
g = "find_till_char"
G = "find_prev_char"
j = "yank"
l = "undo"
L = "redo"
u = "insert_mode"
U = "insert_at_line_start"
y = "open_below"
Y = "open_above"
";" = "paste_after"
":" = "paste_before"
r = "select_regex"
R = "split_selection"
s = "delete_selection"
t = "find_next_char"
T = "find_prev_char"
D = "goto_line"
n = "move_visual_line_down"
N = "join_selections"
e = "move_visual_line_up"
E = "keep_selections"
i = "move_char_right"
o = "collapse_selection"
O = "command_mode"
k = "search_next"
K = "search_prev"

C-f = "page_down"
C-s = "page_cursor_half_down"
C-l = "page_cursor_half_up"
C-u = "jump_forward"
C-y = "jump_backward"
C-r = "save_selection"

[keys.select.d]
"d" = "goto_file_start"
"f" = "goto_last_line"
"t" = "goto_file"
"h" = "goto_line_start"
"i" = "goto_line_end"
"r" = "goto_first_nonwhitespace"
"g" = "goto_window_top"
"c" = "goto_window_center"
"b" = "goto_window_bottom"
"s" = "goto_definition"
"j" = "goto_type_definition"
"p" = "goto_reference"
"u" = "goto_implementation"
"k" = "goto_next_buffer"
";" = "goto_previous_buffer"
"n" = "move_line_down"
"e" = "move_line_up"
