theme = "boo_berry"

[editor]
line-number = "relative"
auto-completion = true
text-width = 80
bufferline = "multiple"

[keys.normal]

f = "move_next_word_end"
F = "move_next_long_word_end"
p = "replace"
P = "replace_with_yanked"
g = "find_till_char"
G = "find_prev_char"
j = "yank"
l = "undo"
L = "redo"
u = "insert_mode"
U = "insert_at_line_start"
y = "open_below"
Y = "open_above"
";" = "paste_after"
":" = "paste_before"
r = "select_regex"
R = "split_selection"
s = "delete_selection"
t = "find_next_char"
T = "find_prev_char"
d = "goto_file"
D = "goto_line"
n = "move_visual_line_down"
N = "join_selections"
e = "move_visual_line_up"
E = "keep_selections"
i = "move_char_right"
o = "collapse_selection"
O = "command_mode"
k = "search_next"
K = "search_prev"
