[window]
opacity = 0.7
blur = true
padding = { x = 15, y = 15 }
dynamic_padding = true

[font.normal]
family = "Fira Code"
style = "Regular"

[colors]
cursor = { text = "#6c393c", cursor = "#ecb5bb" }
[colors.search]
matches = { foreground = "#4e186c", background = "#b66fdc" }

[terminal]
shell = "tmux"

[keyboard]
bindings = [
  { key = "U", mode = "Vi", action = "Up" },
  { key = "N", mode = "Vi", action = "Left" },
  { key = "E", mode = "Vi", action = "Down" },
  { key = "I", mode = "Vi", action = "Right" }
]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"
