#!/bin/sh

set -e

echo "Checking for yay..."
if ! command -v yay &>/dev/null; then
  echo "Installing yay..."
  sudo pacman -S --needed git base-devel
  tmpdir=$(mktemp -d)
  git clone https://aur.archlinux.org/yay.git "$tmpdir"
  cd "$tmpdir"
  makepkg -si --noconfirm
  cd -
  rm -rf "$tmpdir"
  yay --version
else
  echo "Yay is already installed!"
fi

pacman_packages=(
  "alsa-utils"
  "arduino-ide"
  "aspnet-runtime"
  "base"
  "base-devel"
  "blueman"
  "clang"
  "cmake"
  "composer"
  "discord"
  "dkms"
  "docker"
  "dolphin"
  "dotnet-runtime"
  "dotnet-sdk"
  "dunst"
  "efibootmgr"
  "firefox"
  "gamemode"
  "gcc"
  "gdb"
  "git"
  "glfw"
  "grim"
  "gwenview"
  "htop"
  "hyprland"
  "hyprpaper"
  "hyprpicker"
  "hyprsunset"
  "intel-ucode"
  "iwd"
  "kitty"
  "krita"
  "libc++"
  "libc++abi"
  "linux"
  "linux-firmware"
  "linux-headers"
  "lld"
  "make"
  "mariadb"
  "nano"
#  "neofetch"
  "neovim"
#  "network-manager-applet"
  "networkmanager"
  "nodejs"
  "noto-fonts-cjk"
  "noto-fonts-emoji"
  "npm"
  "nvidia-dkms"
  "nvtop"
  "obs-studio"
  "ollama"
  "openvpn"
  "pacman-contrib"
  "php"
  "php-apache"
  "php-sqlite"
  "pipewire-alsa"
  "pipewire-jack"
  "pipewire-pulse"
  "polkit-kde-agent"
  "python-pip"
  "qt5-wayland"
  "qt6-wayland"
  "ranger"
  "rust"
  "sddm"
  "slurp"
  "smartmontools"
  "steam"
  "tor"
  "tree"
  "ttf-fira-code"
  "ttf-jetbrains-mono"
  "ttf-jetbrains-mono-nerd"
  "ttf-nerd-fonts-symbols"
  "unzip"
  "valgrind"
  "waybar"
  "wget"
  "wine"
  "wireless_tools"
  "wireplumber"
  "wl-clipboard"
  "xdg-desktop-portal-hyprland"
  "xdg-utils"
  "xf86-input-wacom"
  "xorg-server"
  "xorg-xinit"
  "zig"
  "zip"
  "zoxide"
  "zsh"
)

yay_packages=(
  "ani-cli"
  "bottles"
#  "cava"
  "hyprshade"
  "postman-bin"
  "protonup-qt"
  "rose-pine-cursor"
  "spotify"
#  "termius"
  "tofi"
  "tor-browser-bin"
  "ttf-google-fonts-typewolf"
  "yay"
  "yay-debug"
  "zapzap"
)

# Install from lists
echo "Installing pacman packages..."
sudo pacman -S --needed "${pacman_packages[@]}"

echo "Installing yay packages..."
yay -S --needed --answerclean All "${yay_packages[@]}"
