typeset -U path cdpath fpath manpath
for profile in ${(z)NIX_PROFILES}; do
  fpath+=($profile/share/zsh/site-functions $profile/share/zsh/$ZSH_VERSION/functions $profile/share/zsh/vendor-completions)
done

HELPDIR="/nix/store/1a22v0kyhffmy136i5i5ldq3x4058146-zsh-5.9/share/zsh/$ZSH_VERSION/help"

source /nix/store/dydb3zxxp2flbzwa0yd3x92rwgrbc03x-zsh-autosuggestions-0.7.1/share/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_STRATEGY=(history)


# oh-my-zsh extra settings for plugins

# oh-my-zsh configuration generated by NixOS
plugins=(git z)
ZSH_CUSTOM="/home/liz/.config/oh-my-zsh-custom"
ZSH_THEME="sobole"
source $ZSH/oh-my-zsh.sh

# History options should be set in .zshrc and after oh-my-zsh sourcing.
# See https://github.com/nix-community/home-manager/issues/177.
HISTSIZE="10000"
SAVEHIST="10000"

HISTFILE="$HOME/.zsh_history"
mkdir -p "$(dirname "$HISTFILE")"

setopt HIST_FCNTL_LOCK
unsetopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
unsetopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_SAVE_NO_DUPS
unsetopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
unsetopt HIST_EXPIRE_DUPS_FIRST
setopt SHARE_HISTORY
unsetopt EXTENDED_HISTORY


alias -- calc=/media/OS/utils/calc/target/release/calc
alias -- cleangens='sudo nix-collect-garbage -d'
alias -- currency=/media/OS/utils/currency/target/release/currency
alias -- dotflake='sx ~/dotties/flake.nix'
alias -- e='emacs -nw'
alias -- econf='e ~/.config/emacs.d/config.el'
alias -- fact='nix-instantiate --eval /media/OS/codes/languages/nix/factorial/factorial.nix --arg num'
alias -- genlist='sudo nix-env --list-generations -p /nix/var/nix/profiles/system'
alias -- homeconf='x ~/dotties/home/home.nix'
alias -- homerb='nix run github:nix-community/home-manager -- switch --flake ~/dotties#liz && source ~/.zshrc'
alias -- i3conf='x ~/dotties/config/i3/config'
alias -- nixcg=nix-collect-garbage
alias -- nixconf='sx ~/dotties/system/configuration.nix'
alias -- nixrb='cd /etc/nixos && sudo nix flake update && sudo nixos-rebuild switch --flake /etc/nixos#nixos'
alias -- p=/media/OS/codes/languages/rust/projects/pls/target/release/pls
alias -- se='sudo -E emacs -nw'
alias -- search='cd /media/OS/codes/languages/rust/projects/search && ./target/release/search'
alias -- sx='sudo -E hx'
alias -- sysflake='sx /etc/nixos/flake.nix'
alias -- todo=/media/OS/utils/todo/target/release/todo
alias -- x=hx
source /nix/store/cjvvc0mnz2bjavbb83i0ia88b0j0cccr-zsh-syntax-highlighting-0.8.0/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
ZSH_HIGHLIGHT_HIGHLIGHTERS+=()


